### ISSUE TITLE
能否集成一个APP页面组件开发库，类似nutui 之类的，专门为app 定制了大量组件库的框架？

### ISSUE THREAD

**Issue by RFSN** [xxxxue/autox-super-kit#4]
能否集成一个APP页面组件开发库，类似nutui 之类的，专门为app 定制了大量组件库的框架？

**Comment by RFSN** [comment]
比如京东提供的  NutUI-Vue 这样的库

**Comment by xxxxue** [comment]
web 分支那个前端是可以随意改的.  改起来非常的容易,   
你可以 `用任意 前端框架 和 UI 组件库` .
根据 UI 组件库官网 的步骤 就能安装上.

**Comment by wploey** [comment]
大佬有空整个打包vue的template
