### ISSUE TITLE
npm run dev保存时编译autox崩溃

### ISSUE THREAD

**Issue by wploey** [xxxxue/autox-super-kit#5]
项目代码用到了线程， npm run dev后，按1，手机连接完，按2运行项目，接下来修改代码重新编译发送运行时就崩溃了

autoxjs版本： 6.5.5
设备：红米K50 安卓12
错误日志
Version: 655
Android: 31
java.lang.InterruptedException: 
java.lang.RuntimeException:Unable to pause activity {org.autojs.autoxjs.v6/com.stardust.autojs.execution.ScriptExecuteActivity}: java.lang.InterruptedException
android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5212)
......
Caused by:
java.lang.InterruptedException:
kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
org.autojs.autojs.devplugin.DevPlugin$Connection.log(DevPlugin.kt:330)
org.autojs.autojs.devplugin.DevPlugin.log(DevPlugin.kt:91)
org.autojs.autojs.autojs.AutoJs$3.println(AutoJs.java:119)
com.stardust.autojs.core.console.ConsoleImpl.println(ConsoleImpl.java:137)
com.stardust.autojs.runtime.api.AbstractConsole.printf(AbstractConsole.java:26)
com.stardust.autojs.runtime.api.AbstractConsole.error(AbstractConsole.java:66)
com.stardust.autojs.core.console.ConsoleImpl.error(ConsoleImpl.java:356)
com.stardust.autojs.ScriptEngineService$Companion$GLOBAL_LISTENER$1.onException(ScriptEngineService.kt:225)
com.stardust.autojs.execution.ScriptExecutionObserver.onException(ScriptExecutionObserver.java:29)
com.stardust.autojs.execution.ScriptExecuteActivity.onException(ScriptExecuteActivity.kt:77)
com.stardust.autojs.execution.ScriptExecuteActivity.finish(ScriptExecuteActivity.kt:115)
com.stardust.autojs.engine.LoopBasedJavaScriptEngine.forceStop(LoopBasedJavaScriptEngine.java:82)
com.stardust.autojs.runtime.ScriptRuntime.exit(ScriptRuntime.java:378)
com.stardust.autojs.runtime.ScriptRuntime.exit(ScriptRuntime.java:387)
com.stardust.autojs.execution.ScriptExecuteActivity.emit(ScriptExecuteActivity.kt:198)
com.stardust.autojs.execution.ScriptExecuteActivity.onPause(ScriptExecuteActivity.kt:148)
android.app.Activity.performPause(Activity.java:8392)
android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5202)
android.app.ActivityThread.performPauseActivity(ActivityThread.java:5163)
android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5115)
android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8307)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by xxxxue** [comment]
你可以用 `前几个版本的 autox` 试一试. 看看会报错吗

**Comment by wploey** [comment]
代码重新整理后，就没出现了，玄学

**Comment by wploey** [comment]
> 代码重新整理后，就没出现了，玄学

找到原因了
是添加了这段代码就会
```
//当离开本界面时保存taskList
ui.emitter.on("pause", () => {
  main.start.attr('visibility', 'visible');
  store.put("items", taskList);
  toastLog('方案已保存')
});
```

@xxxxue

**Comment by xxxxue** [comment]
> > 代码重新整理后，就没出现了，玄学
> 
> 找到原因了
> 是添加了这段代码就会
> ```
> //当离开本界面时保存taskList
> ui.emitter.on("pause", () => {
>   main.start.attr('visibility', 'visible');
>   store.put("items", taskList);
>   toastLog('方案已保存')
> });
> ```
> 
> @xxxxue 

看来这是autojs自己内部的问题，
框架只是发送 运行和停止 信号。
和vscode插件功能一模一样。
